SUPABASE_URL=https://haxqewunbckhhvlliwht.supabase.co
SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhheHFld3VuYmNraGh2bGxpd2h0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMzQ2MDUsImV4cCI6MjA1ODkxMDYwNX0.ysAWh1XqAd4HoQiy4mIeIV8KUfwEut2YbqvgIQFPhsQ
