SUPABASE_URL=https://iesijewqgwjuakbpgfgg.supabase.co
SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imllc2lqZXdxZ3dqdWFrYnBnZmdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1Mjg2ODUsImV4cCI6MjA1NzEwNDY4NX0.wIwPA7Qjho1CG9HEH__ZGDFjfCyFamY1c9x6ODE4L7Y
